#!/bin/bash

VER=$1
SUB=$2

rm -f repack_zip/boot/zImage

mv arch/arm64/boot/Image.gz-dtb repack_zip/boot/zImage

cd repack_zip

if [ ! $VER ] && [ ! $SUB ]; then
	zip -r ../../release_testing/Clarity-Testing-AOSP_HM4X.zip *
else
	zip -r ../../release_santoni/Clarity-v$VER.$SUB-AOSP_HM4X.zip *
fi
